---
title: "Datos de cantones de Costa Rica"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r paquetes, message=FALSE,warning=FALSE}
library(dplyr)
library(sf)
library(leaflet)
library(DT)
library(ggplot2)
library(plotly)
```

```{r lectura-datos,message=FALSE,warning=FALSE}
cantones <-
  st_read(dsn = "cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Mapa de cantones 

```{r mapa, message=FALSE,warning=FALSE}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = cantones, weight = 1.0)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Tabla de cantones

```{r tabla, message=FALSE,warning=FALSE}
cantones %>%
  select(provincia, canton, area) %>%
  datatable(options = list(
    pageLength = 7,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```

### Gráfico de cantones

```{r grafico, message=FALSE,warning=FALSE}
ggplot2_grafico_cantones <-
cantones %>%
  slice_max(area, n = 15) %>% 
  ggplot(aes(x = reorder(canton, area), y = area)) +
  geom_bar(stat = "identity") +
  ggtitle("Área de cada cantón") +
  xlab("Cantón") +
  ylab("Área") +
  coord_flip() 

ggplotly(ggplot2_grafico_cantones) %>% config(locale = 'es')
```

